name: Generate and Upload Reports

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'flake.*'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'flake.*'
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  generate-reports:
    name: Generate reports
    strategy:
      matrix:
        os:
          - name: ubuntu-24.04-arm
            arch: arm64
          - name: ubuntu-latest
            arch: amd64

    runs-on: ${{ matrix.os.name }}

    # Skip this job if the commit was made by the GitHub Actions bot (prevents infinite CI loops)
    if: github.actor != 'github-actions[bot]'

    env:
      OUTPUT_DIR: build/reports
      REPORT_DIR: .github/reports/${{ matrix.os.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: ${{ github.repository_owner }}-hello-world-sizes
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run Nix flake to generate reports | ${{ matrix.os.arch }}
        run: nix run

      # Copy report to timestamped and latest locations
      - name: Save report with timestamp
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          mkdir -p $REPORT_DIR/

          metrics="binary_size memory_usage"
          for metric in $metrics; do
            cp $OUTPUT_DIR/$metric.png "$REPORT_DIR/${metric}_$TIMESTAMP.png"
            cp $OUTPUT_DIR/$metric.png $REPORT_DIR/${metric}_latest.png
          done

          echo "Report saved as $REPORT_DIR/$TIMESTAMP.png"

      - name: Upload all reports as a single artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-reports
          path: ${{ env.OUTPUT_DIR }}/*.png
          retention-days: 30

      - name: Commit and push reports
        if: github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $REPORT_DIR/
          git commit -m "ci: update latest report artifact [auto]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
